/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package media.core.rtsp.sdp

object SdpParser {
    fun parse(string: String): SdpSession {
        val session = SdpSession()
        session.parse(string)
        return session
    }
}
